export const elements = {
    searchInput: document.getElementById("searchInput"),
    searchBtn: document.getElementById("searchBtn"),
    apiKey: document.getElementById("apiKey"),
    apiKeyBtn: document.getElementById("apiKeyBtn"),
    apiKeyModal: document.getElementById("apiKeyModal"),
    saveApiKeyBtn: document.getElementById("saveApiKeyBtn"),
    results: document.getElementById("results"),
    loading: document.getElementById("loading"),
    error: document.getElementById("error"),
    themeToggle: document.getElementById("themeToggle"),
    bookmarksBtn: document.getElementById("bookmarksBtn"),
    bookmarkCount: document.getElementById("bookmarkCount"),
    bookmarksModal: document.getElementById("bookmarksModal"),
    bookmarksList: document.getElementById("bookmarksList"),
    clusterModal: document.getElementById("clusterModal"),
    clusterTitle: document.getElementById("clusterTitle"),
    clusterDetails: document.getElementById("clusterDetails"),
    aiSection: document.getElementById("aiSection"),
    nlQuerySection: document.getElementById("nlQuerySection"),
    nlQueryInput: document.getElementById("nlQueryInput"),
    nlQueryBtn: document.getElementById("nlQueryBtn"),
    nlQueryResponse: document.getElementById("nlQueryResponse"),
    resultsSection: document.getElementById("resultsSection"),
    resultsHeader: document.getElementById("resultsHeader"),
    generateSummary: document.getElementById("generateSummary"),
    filterToggle: document.getElementById("filterToggle"),
    filters: document.getElementById("filters"),
    exportBtn: document.getElementById("exportBtn"),
    viewMode: document.getElementById("viewMode"),
    maxResults: document.getElementById("maxResults"),
    maxResultsValue: document.getElementById("maxResultsValue"),
    aiSummary: document.getElementById("aiSummary"),
    sentimentAnalysis: document.getElementById("sentimentAnalysis"),
};

